language: ruby
rvm:
  - 2.2
env:
  - "TEST_GROUP=1"
  - "TEST_GROUP=2"
  - "TEST_GROUP=3"
  - "TEST_GROUP=4"
  - "TEST_GROUP=5"
  - "TEST_GROUP=6"
  - "TEST_GROUP=7"
  - "TEST_GROUP=8"
  - "TEST_GROUP=9"
  - "TEST_GROUP=10"
before_script:
 - gem install bundler
 - bundler i
 - createdb myapp_test
script:
 - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: "bb325b2a-3bcd-4935-ae6f-b30e76f70559"
  app: afternoon-beach-16255
  run: "rake db:migrate"
  on:
      branch: master