language: ruby
rvm:
  - 2.2
before_script:
 - gem install bundler
 - bundler i
 - createdb myapp_test
script:
 - bundle exec rspec
after_deploy:
 - git reset --hard HEAD
deploy:
  provider: heroku
  api_key:
    secure: "bb325b2a-3bcd-4935-ae6f-b30e76f70559"
  app: afternoon-beach-16255
  run: "rake db:migrate"
  on:
      branch: master